### PR TITLE
fix: backend validation does not prevent responses on hidden fields

### LINKED ISSUE #732: Backend validation does not prevent responses on hidden fields
Related to #7

Steps to reproduce:
- Create form with short text field hidden behind radio button
- Programatically submit short text field response without radio response. Submission is successful.

### PR DESCRIPTION
**Pull request by tshuli**
## Problem

Closes #732
## Solution
- Add check for isVisible in validateField()
- Also updated unit tests

## Tests
- [ ] Create a form with Yes/No field, and a Number Field hidden behind it. Attempt to submit a response programatically with the number field still hidden. Submission should fail.
- [ ] Now unhide the Number Field. Attempt to submit a response on the number field normally. Submission should pass.
- [ ] Create email mode form with all field types (including Yes/No) hidden behind a Yes/No field. Submit while keeping the fields hidden. Submission should pass.

### CODE REVIEW

File: src/app/utils/field-validation/index.ts [hunk 1]
```diff
@@ -41,6 +52,41 @@ const doFieldTypesMatch = (
...
+ * Returns true if response appears on a hidden field.
+ * This may happen if a submission is made programatically to try and bypass form logic.
+ * @param response The submitted response
+ */
+const isResponsePresentOnHiddenField = (
+  response:
+    | ISingleAnswerResponse
+    | ICheckboxResponse
+    | ITableResponse
+    | IAttachmentResponse,
```
Comment (liangyuanruo) [inline src/app/utils/field-validation/index.ts:65]: does a union of these types already exist?

File: src/app/utils/field-validation/index.ts [hunk 2]
```diff
@@ -41,6 +52,41 @@ const doFieldTypesMatch = (
...
+    if (!response.isVisible && response.answerArray[0].length > 0) {
+      return true
+    }
+  }
+  if (isProcessedAttachmentResponse(response)) {
+    if (!response.isVisible && response.filename.trim() !== '') {
+      return true
+    }
+  }
+  return false
```
Comment (liangyuanruo) [inline src/app/utils/field-validation/index.ts:87]: i think we should be using an `if-else if-else` structure here for the avoidance of doubt

File: src/types/response/guards.ts [hunk 3]
```diff
@@ -23,3 +26,34 @@ export const isProcessedSingleAnswerResponse = (
...
+  )
+}
+
+export const isProcessedTableResponse = (
+  response: any,
+): response is ProcessedTableResponse => {
+  return (
+    'answerArray' in response &&
+    Array.isArray(response.answerArray) &&
+    Array.isArray(response.answerArray[0]) &&
```
Comment (liangyuanruo) [inline src/types/response/guards.ts:46]: this check looks weird - should every element in `answerArray` be an array? and should every element in it be of string type?

Comment (liangyuanruo) [reply src/types/response/guards.ts:46]: there are important ramifications for the type safety of downstream code, if the type guard is not written as strictly as possible

Comment (liangyuanruo) [reply src/types/response/guards.ts:46]: you may also want to introduce new subtypes with additional type guards for each row of answers, and build your way up to having a bigger `isProcessedTableResponse`. i suspect the subtypes will come in useful for composing table row validators

File: tests/unit/backend/utils/field-validation/dropdown-validation.spec.js [hunk 4]
```diff
@@ -133,4 +133,22 @@ describe('Dropdown validation', () => {
       new ValidateFieldError('Invalid answer submitted'),
     )
   })
+  it('should disallow responses submitted for hidden fields', () => {
+    const formField = {
+      _id: 'ddID',
+      fieldType: 'dropdown',
+      fieldOptions: ['KISS', 'DRY', 'YAGNI'],
```
Comment (liangyuanruo) [inline tests/unit/backend/utils/field-validation/dropdown-validation.spec.js:140]: lol nice one

File: src/app/utils/field-validation/index.ts (hunk 1 above)
Comment (tshuli) [reply src/app/utils/field-validation/index.ts:65]: actually yes, `type FieldResponse`. will use that instead

File: src/app/utils/field-validation/index.ts (hunk 2 above)
Comment (tshuli) [reply src/app/utils/field-validation/index.ts]: edited

File: src/types/response/guards.ts (hunk 3 above)
Comment (tshuli) [reply src/types/response/guards.ts]: thanks! see if the edits work

File: tests/unit/backend/utils/field-validation/date-validation.spec.js [hunk 5]
```diff
@@ -462,4 +462,34 @@ describe('Date field validation', () => {
 
     jasmine.clock().uninstall()
   })
+
+  it('should disallow responses submitted for hidden fields', () => {
+    jasmine.clock().install()
```
Comment (liangyuanruo) [inline tests/unit/backend/utils/field-validation/date-validation.spec.js:467]: nit: to move jasmine clock install/uninstall to `beforeAll` and `afterAll`

**Review by liangyuanruo — APPROVED** [review]

File: src/app/utils/field-validation/index.ts [hunk 6]
```diff
@@ -41,6 +47,35 @@ const doFieldTypesMatch = (
...
+      return true
+    }
+  } else if (isProcessedCheckboxResponse(response)) {
+    if (!response.isVisible && response.answerArray.length > 0) {
+      return true
+    }
+  } else if (isProcessedTableResponse(response)) {
+    if (
+      !response.isVisible &&
+      flattenDeep(response.answerArray).join('').length > 0
```
Comment (liangyuanruo) [inline src/app/utils/field-validation/index.ts:67]: consider testing the presence of an answer by traversing each element in this 2D array, instead of performing string concatenation.

File: src/types/response/guards.ts [hunk 7]
```diff
@@ -23,3 +28,44 @@ export const isProcessedSingleAnswerResponse = (
...
+}
+
+export const isProcessedTableResponse = (
+  response: any,
+): response is ProcessedTableResponse => {
+  return (
+    'answerArray' in response &&
+    Array.isArray(response.answerArray) &&
+    // Check that all elements in answerArray are table rows
+    response.answerArray.every((arr: any) => isTableRow(arr)) &&
```
Comment (liangyuanruo) [inline src/types/response/guards.ts:58]: each array in `answerArray` should also be of the same length

File: tests/unit/backend/utils/field-validation/date-validation.spec.js (hunk 5 above)
Comment (tshuli) [reply tests/unit/backend/utils/field-validation/date-validation.spec.js]: edited

File: src/app/utils/field-validation/index.ts (hunk 6 above)
Comment (tshuli) [reply src/app/utils/field-validation/index.ts]: edited, see if ok

File: src/types/response/guards.ts (hunk 7 above)
Comment (tshuli) [reply src/types/response/guards.ts]: edited, see if ok

File: src/types/response/guards.ts [hunk 8]
```diff
@@ -23,3 +28,50 @@ export const isProcessedSingleAnswerResponse = (
...
+  response: any,
+): response is ProcessedTableResponse => {
+  if (
+    'answerArray' in response &&
+    Array.isArray(response.answerArray) &&
+    // Check that all elements in answerArray are table rows
+    response.answerArray.every((arr: any) => isTableRow(arr))
+  ) {
+    // Check that all arrays in answerArray have the same length
+    const subArrLength: number = response.answerArray[0].length
```
Comment (liangyuanruo) [inline src/types/response/guards.ts:61]: is it possible that `response.answerArray[0]` is `undefined`?

**Review by liangyuanruo — APPROVED** [review]
Approving first, please address previous comment before merging.

File: src/types/response/guards.ts (hunk 8 above)
Comment (tshuli) [reply src/types/response/guards.ts:63]: thanks for pointing out, i've added an additional check that response.answerArray[0] must be a tableRow
