### PR TITLE
fix(v2): update hashbang routing

### LINKED ISSUE #4809: [0.5] Visiting hashbanged admin URL does not redirect correctly
e.g. going to
https://staging-alt.form.gov.sg/#!/630c666edb37bb001248ceed/admin

redirects me to
https://staging-alt.form.gov.sg/dashboard/admin/form/630c666edb37bb001248ceed

which doesn't work because there's an extra `dashboard` in the URL.

### PR DESCRIPTION
**Pull request by wanlingt**
## Problem

Hashbanged admin URL was not routing correctly
 
Closes #4809

## Solution
- Update routing for admin form and preview
- Add routing for examples page

**Bug fixes**
- Updated `user.routes` test

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

## Tests
Each of the following routes should redirect to the non-hangbang React version - (remember to replace `formId`)
https://staging.form.gov.sg/#!/63033f67721bbb0012521e2d
https://staging.form.gov.sg/#!/${formId}/admin
https://staging.form.gov.sg/#!/${formId}/preview
https://staging.form.gov.sg/#!/forms
https://staging.form.gov.sg/#!/examples => 404

### CODE REVIEW

File: frontend/src/app/HashRouterElement.tsx [hunk 1]
```diff
@@ -31,17 +31,20 @@ const hashRouteMapper = [
...
   {
     regex: /^#!\/(?<formid>[0-9a-fA-F]{24})\/preview$/,
     getTarget: (m: FormRegExpMatchArray) =>
-      `${ROOT_ROUTE}/admin/form/${m.groups.formid}/preview`,
+      `/admin/form/${m.groups.formid}/preview`,
   },
   {
     regex: /^#!\/examples$/,
-    getTarget: (m: FormRegExpMatchArray) => `${ROOT_ROUTE}/admin`,
+    getTarget: (m: FormRegExpMatchArray) => `${LANDING_ROUTE}`,
```
Comment (karrui) [inline frontend/src/app/HashRouterElement.tsx]: should this go to 404 instead

File: frontend/src/app/HashRouterElement.tsx [hunk 2]
```diff
@@ -31,17 +31,20 @@ const hashRouteMapper = [
...
+  },
+  {
+    regex: /^#!\/forms$/,
+    getTarget: (m: FormRegExpMatchArray) => `${ROOT_ROUTE}`,
```
Comment (karrui) [inline frontend/src/app/HashRouterElement.tsx]: should we take the chance to rename `ROOT_ROUTE` to `DASHBOARD_ROUTE`?

**Review by karrui — APPROVED** [review]
