### PR TITLE
fix: rm white box for payment preview when disabled

### LINKED ISSUE #6340: When payment is not enabled on a form, a white box is still rendered where the payment preview usually is
image

### PR DESCRIPTION
**Pull request by LinHuiqing**
## Problem

White box is still shown where payment preview is rendered when payment is enabled.

Closes https://github.com/opengovsg/FormSG/issues/6340

## Solution

Only show the white box that wraps payment preview when payment is enabled.

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

**Bug Fixes**:

- Moves `payment.enabled` check up to include the white box wrapping payment preview

## Before & After Screenshots

**BEFORE**:

Builder mode:

Screenshot 2023-05-17 at 1 40 26 PM

Preview mode:

Screenshot 2023-05-17 at 1 40 33 PM

Public form:

Screenshot 2023-05-17 at 1 40 43 PM

**AFTER**:

Builder mode:

Screenshot 2023-05-17 at 1 37 42 PM

Preview mode:

Screenshot 2023-05-17 at 1 38 27 PM

Public form:

Screenshot 2023-05-17 at 1 37 55 PM

## Tests

- [ ] Create a storage-mode form
- [ ] With payment disabled, go to builder mode. There should be no white box or payment preview shown to the right.
- [ ] Enable payment. The payment preview should appear (builder mode).
- [ ] Go to preview the form in preview mode. There should be no white box or payment preview at the bottom of the form.
- [ ] Open the form. Go to the respondent view of the form. There should be no white box or payment preview at the bottom of the form.

### CODE REVIEW

File: frontend/src/features/public-form/components/FormFields/FormFields.tsx [hunk 1]
```diff
@@ -163,19 +163,20 @@ export const FormFields = ({
...
-            px={{ base: '1rem', md: '2.5rem' }}
-          >
-            <PaymentPreview
-              colorTheme={colorTheme}
-              paymentDetails={form?.payments_field}
-            />
-          </Box>
-        )}
+        {form?.responseMode === FormResponseMode.Encrypt &&
+          form?.payments_field.enabled && (
```
Comment (foochifa) [inline frontend/src/features/public-form/components/FormFields/FormFields.tsx:167]: Just a nit: I think as we moved the validation of payment details being enabled above the box, we can now confirm that the `paymentDetails` thats being passed into `PaymentPreview` is defined. 

That can also help to remove the 

`if (!paymentDetails || !paymentDetails.enabled) return null` check within `PaymentPreview` too

Comment (LinHuiqing) [reply frontend/src/features/public-form/components/FormFields/FormFields.tsx:167]: thanks! done in [e896b37](https://github.com/opengovsg/FormSG/pull/6342/commits/e896b37be6c91de0c872ea34d356e140b1a416a7)

**Review by foochifa — APPROVED** [review]
LGTM! Thanks huiqing
