### PR TITLE
fix: add payout pending section to individual response page

### LINKED ISSUE #6143: Make payout status always visible on payments details in response
Admins should not have to wonder whether they have received the payout or not.

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
We want to display the payout pending section even when payout details have not come in.

Closes #6143 

## Solution
Change the value of the payout details to "-" when no payout details are sent to the frontend. Display these with the appropriate tag for the payout "status", as per [figma](https://www.figma.com/file/CMq0CJtawn7NGM7Zdpi8Ti/Form-Design-Master?node-id=16608-163982&t=QhakbMRTzLni6fwD-4).

**Breaking Changes** 
- No - this PR is backwards compatible  

## Before & After Screenshots

Payout pending
Screenshot 2023-04-28 at 10 53 24 AM

Payout success
Screenshot 2023-04-28 at 10 53 16 AM

### CODE REVIEW

File: frontend/src/features/admin-form/responses/IndividualResponsePage/PaymentSection.tsx [hunk 1]
```diff
@@ -66,24 +36,19 @@ export const PaymentSection = ({
       ? { label: 'Disputed', colorScheme: 'warning' }
       : undefined // The remaining options should never appear.
 
+  const payoutTagProps =
+    payment.payoutId || payment.payoutDate
```
Comment (foochifa) [inline frontend/src/features/admin-form/responses/IndividualResponsePage/PaymentSection.tsx:40]: Just curious but `payoutId` and `payoutDate` will always exists together right? i.e. 0 || 0 and 1 || 1?

**Review by foochifa — APPROVED** [review]
Lgtm thanks Justyn!

For tests was wondering if we could somehow trigger payouts -> was trying manual payouts but it killed my backend container 😅 
image


But firstly maybe can just manually edit the db (which is what I guess was the screenshot)
We can document the steps down too like go to payments doc -> add payout.payoutId && payout.payoutDate.

File: frontend/src/features/admin-form/responses/IndividualResponsePage/PaymentSection.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/features/admin-form/responses/IndividualResponsePage/PaymentSection.tsx:40]: yup, this is a bit of a deficiency in the dto. but to avoid complication, i think this is fine. In principle, if any one of them is there, we should consider it successful (since a payout is already "known" to occur by ID or by date).
