### PR TITLE
fix: meta tags for public form pages

### LINKED ISSUE #5589: meta tags are not showing up correctly for public form pages
**Describe the bug**
The title, description and image for the meta tags are defaulting to the form.gov.sg ones, although they should be different

**Expected behavior**
Related to #5114 

Non-public form pages
image

Public form pages (Open forms)
image

Also, try to set up the og_image to be a fully qualified url too (dynamically - probably need to read the host name from the request headers)

### PR DESCRIPTION
**Pull request by wanlingt**
## Problem

Social media previews were not being generated correctly for public forms.

`formResult.value.status` was `undefined` as `status` was not retrieved in the form result. Hence the check for public forms was always returning `false`, and the default meta tags would be used for public forms, instead of the public form-specific meta tags.

Closes #5589

## Solution

To fix this, I specified `status` when retrieving the form using `FormService.retrieveFormKeysById`.

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

## Before & After Screenshots

**AFTER**:

Public form
image

Private form
image

## Tests

[Preview and generate](https://www.opengraph.xyz/) Open Graph meta tags, check that `title`, `description` and `image` are populated for
- [x] public form
- [x] private form

### CODE REVIEW

File: src/app/modules/react-migration/react-migration.controller.ts [hunk 1]
```diff
@@ -216,9 +217,10 @@ export const servePublicForm: ControllerHandler<
   })
 
   if (showReact) {
-    return serveFormReact(
+    const isPublicForm = Boolean(
       !formResult.isErr() && formResult.value.status === FormStatus.Public,
-    )(req, res, next)
+    )
+    return serveFormReact(/* isPublic= */ isPublicForm)(req, res, next)
```
Comment (tshuli) [inline src/app/modules/react-migration/react-migration.controller.ts]: dangling comment?

**Review by tshuli — APPROVED** [review]
minor nit but lgtm!

File: src/app/modules/react-migration/react-migration.controller.ts [hunk 2]
```diff
@@ -216,9 +217,10 @@ export const servePublicForm: ControllerHandler<
   })
 
   if (showReact) {
-    return serveFormReact(
+    const isPublicForm = Boolean(
```
Comment (timotheeg) [inline src/app/modules/react-migration/react-migration.controller.ts]: /nit the `Boolean()` wrapper should not be necessary. Both operands of the logical AND operator produce booleans, so the type should already be correct.

File: src/app/modules/react-migration/react-migration.controller.ts (hunk 1 above)
Comment (wanlingt) [reply src/app/modules/react-migration/react-migration.controller.ts]: removed in [00b75a7](https://github.com/opengovsg/FormSG/pull/5799/commits/00b75a7cc63e73d54ee8d1b501676332a0572be1)

File: src/app/modules/react-migration/react-migration.controller.ts (hunk 2 above)
Comment (wanlingt) [reply src/app/modules/react-migration/react-migration.controller.ts]: removed in [00b75a7](https://github.com/opengovsg/FormSG/pull/5799/commits/00b75a7cc63e73d54ee8d1b501676332a0572be1)
