### PR TITLE
fix: add types to RequestHandler in submitEncryptModeForm

### LINKED ISSUE #1854: submitEncryptModeForm handler is not typed
The `submitEncryptModeForm` controller does not contain generic type arguments for Express's `RequestHandler`. This means that the body, route parameters and query parameters are typed as either `any` or `string`, even if they are `undefined` at runtime, so the entire controller is not type-safe.

Generic arguments should be added to `RequestHandler` in order to ensure type safety. Reference can be taken from `submitEmailModeForm` as the arguments will be quite similar.

### PR DESCRIPTION
**Pull request by frankchn**
## Problem
Closes #1854 

## Solution
Adds relevant types

### CODE REVIEW

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts [hunk 1]
```diff
@@ -57,11 +58,28 @@ const EncryptSubmission = getEncryptSubmissionModel(mongoose)
...
 
-const submitEncryptModeForm: RequestHandler = async (req, res) => {
+const submitEncryptModeForm: RequestHandler<
+  { formId: string },
+  {
+    message: string
+    submissionId?: string
+    spcpSubmissionFailure?: boolean
+    isPageFound?: boolean
+    formTitle?: string
```
Comment (mantariksh) [inline src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:68]: I think you can remove `isPageFound` and `formTitle`. they're not used by the frontend.

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts [hunk 2]
```diff
@@ -57,11 +58,28 @@ const EncryptSubmission = getEncryptSubmissionModel(mongoose)
...
+  },
+  {
+    responses: FieldResponse[]
+    encryptedContent: string
+    isPreview: boolean
+    attachments?: Record<string, unknown>
+    version: number
+  },
```
Comment (mantariksh) [inline src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:76]: can we reuse `EncryptSubmissionDto` instead?

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts [hunk 3]
```diff
@@ -57,11 +58,28 @@ const EncryptSubmission = getEncryptSubmissionModel(mongoose)
...
+  { captchaResponse?: unknown }
```
Comment (liangyuanruo) [inline src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:77]: I reckon it would help future developers if we gave meaningful names to these types, instead of anonymously inlining them here

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts [hunk 4]
```diff
@@ -57,11 +58,28 @@ const EncryptSubmission = getEncryptSubmissionModel(mongoose)
...
+> = async (req, res) => {
   const { formId } = req.params
   const logMeta = {
     action: 'handleEncryptedSubmission',
-    ...createReqMeta(req),
+    ...createReqMeta(req as Request),
```
Comment (liangyuanruo) [inline src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:82]: can we avoid typecasts? this is related to the inlined types above, right?

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts (hunk 1 above)
Comment (frankchn) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:68]: I think it is still used in some bits of the code right? https://github.com/opengovsg/FormSG/blob/aecc1dbd44b4258584819a2b3e822347c1446be9/src/public/modules/forms/services/form-error.client.factory.js#L40-L44

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts (hunk 4 above)
Comment (frankchn) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:82]: Hmm without this there is a type error -- we are doing the same thing in `submitEmailModeForm` so I think it is OK?

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts (hunk 3 above)
Comment (frankchn) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:77]: Any examples? I've changed part of this to use `EncryptSubmissionDto` instead. Should I do similar things for the rest of them?

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts (hunk 1 above)
Comment (mantariksh) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:67]: yup they're used elsewhere, but not in this particular case of when storage mode submissions failing.

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts (hunk 4 above)
Comment (karrui) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:75]: Should be ok for now; will be fixed when I reopen #1848

Comment (liangyuanruo) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:75]: ok @karrui will leave to u to track this

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts (hunk 3 above)
Comment (liangyuanruo) [reply src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts]: yes that would help!

**Review by mantariksh — APPROVED** [review]
