### PR TITLE
fix(form-v2): form footer follows form's colour scheme

### LINKED ISSUE #4443: React public form footer not respecting form color theme, wrong padding
Screenshot 2022-08-01 at 11 00 02 AM

### PR DESCRIPTION
**Pull request by wanlingt**
## Problem

Public form footer does not follow the form's colour theme. Also, padding is wrong for forms with sections.

Closes #4443 

## Solution

- Pass in a form's colour scheme to  `FormFooter`'s `containerProps`
- Remove unnecessary `Spacer`

## Before & After Screenshots

**BEFORE**:
Refer to issue

**AFTER**:
image

### CODE REVIEW

File: frontend/src/app/AppFooter.tsx [hunk 1]
```diff
@@ -3,7 +3,7 @@ import Footer, { FooterProps } from '~components/Footer'
 
 type AppFooterProps = Pick<
   FooterProps,
-  'variant' | 'containerProps' | 'compactMonochromeLogos'
+  'variant' | 'containerProps' | 'compactMonochromeLogos' | 'bgColorScheme'
```
Comment (karrui) [inline frontend/src/app/AppFooter.tsx]: i know this is WIP but just reviewing first hehe. I don't think we need a new prop, since there already is `containerProps` that the parent can use

File: frontend/src/features/public-form/components/FormFooter/FormFooter.tsx [hunk 2]
```diff
@@ -32,7 +36,7 @@ export const FormFooter = (): JSX.Element => {
         >
           <Box id={captchaContainerId} />
           <Box w="100%">
-            <AppFooter variant="compact" />
+            <AppFooter variant="compact" bgColorScheme={bgColor} />
```
Comment (karrui) [inline frontend/src/features/public-form/components/FormFooter/FormFooter.tsx]: instead of bgColorScheme, we could use `containerProps` instead:

```tsx
<AppFooter 
  variant="compact" 
  containerProps={{
    bg,
  }} 
/>
```

Comment (wanlingt) [reply frontend/src/features/public-form/components/FormFooter/FormFooter.tsx]: ohhh makes sense ok!

**Review by timotheeg — APPROVED** [review]
LGTM
