### PR TITLE
fix(authTypes): disable changing of authtype with MyInfo, remove esrvcId box from SGID option

### LINKED ISSUE #4310: SGID auth option should not have e-service ID input

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
Form creators can currently change the authtype from MyInfo to something else while they have MyInfo fields in the form.
Also, we currently show an esrvcId box under the SGID option, which should not occur. 

Closes #4310 and #4312 

## Solution

**Breaking Changes** 
- [X] No - this PR is backwards compatible  

## Screenshots

image

### CODE REVIEW

File: frontend/src/features/admin-form/settings/components/AuthSettingsSection/AuthSettingsSection.tsx [hunk 1]
```diff
@@ -167,3 +187,13 @@ export const AuthSettingsSection = ({
     </Box>
   )
 }
+const esrvcidRequired = (authType: FormAuthType) => {
```
Comment (karrui) [inline frontend/src/features/admin-form/settings/components/AuthSettingsSection/AuthSettingsSection.tsx]: nit: should we move this into an utils folder or move it above the component declaration? this should be declared before being used in the component

**Review by karrui — APPROVED** [review]
lgtm

**Comment by karrui** [comment]
can we also add a new AuthSettings story with the MyInfo state?

File: frontend/src/features/admin-form/settings/components/AuthSettingsSection/AuthSettingsSection.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/features/admin-form/settings/components/AuthSettingsSection/AuthSettingsSection.tsx]: will move it above the component declaration! don't think we need to move it into a utils file unless somewhere else we might need this info? it isn't even enforced in `FormBase` lol

**Comment by justynoh** [comment]
Added a new story for private form with MyInfo fields :)
