### PR TITLE
feat: add radio options to bug report form

### LINKED ISSUE #5185: Add radio buttons for getting categorized feedback from users

### PR DESCRIPTION
**Pull request by wanlingt**
## Problem

We want to get categorised feedback from users.

Closes #5185

## Solution

- Add radio options, which are required to submit the form
- Radio options differ depending on whether it's a public form or admin view
- Allow non-logged-in user to input their email, validate email

**Bug Fixes**:
- Only display `FormErrorIcon` if `children` props exist in `FormErrorMessage`

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

## Before & After Screenshots

**Admin**:

https://user-images.githubusercontent.com/56983748/197731404-89573393-d4fb-45a6-b25f-616885e2c8d1.mov

**Public form**:

https://user-images.githubusercontent.com/56983748/197731414-af0832b0-ffbe-46f3-a097-7ee0cff9c31d.mov

## Tests

Note: remember to add radio options as the last question in the bug report form before testing -

> Question: Why are you switching to the previous FormSG?
> Enable Others
> Disable Required
> Options:
> I couldn’t submit my form
> I couldn’t find a feature I needed
> The new FormSG did not function properly
> I’m not used to the new FormSG

- [x] Submit bug report form from admin view. Check that selection of a radio option is required.
- [x] Submit bug report form from public form view. Check that selection of a radio option is required, email entered should be in the correct format.

### CODE REVIEW

File: frontend/src/features/env/SwitchEnvFeedbackModal.tsx [hunk 1]
```diff
@@ -33,6 +39,14 @@ export interface SwitchEnvModalProps {
   onChangeEnv: () => void
 }
 
+export const ADMIN_RADIO_OPTIONS = [
+  'I couldn’t find a feature I needed',
+  'The new FormSG did not function properly',
+]
+export const PUBLIC_RADIO_OPTIONS = ['I couldn’t submit my form']
+export const COMMON_RADIO_OPTIONS = ['I’m not used to the new FormSG']
+export const FEEDBACK_OTHERS_INPUT_NAME = 'others-input'
```
Comment (karrui) [inline frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: nit: suggest something less likely to collide, maybe `react-feedback-others-input`?

File: frontend/src/features/env/SwitchEnvFeedbackModal.tsx [hunk 2]
```diff
@@ -71,6 +99,8 @@ export const SwitchEnvFeedbackModal = ({
     setShowThanksPage(false)
   }, [onChangeEnv, onClose])
 
+  const isPublicFormPage = window.location.pathname.match(publicFormPath)
```
Comment (karrui) [inline frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: this is throwaway code, so it's a nit:

should we use the `AdminSwitchEnvMessage`/`PublicSwitchEnvMessage` to inject the radio options as props instead of creating it here? Removes the conditionals and improves readability:

```tsx
<Radio.RadioGroup>
  {radioOptions.map(option => 
    ...
  }
  <Radio.OthersWrapper ... />
</Radio.RadioGroup>
```

File: shared/types/env.ts [hunk 3]
```diff
@@ -10,4 +10,5 @@ export interface SwitchEnvFeedbackFormBodyDto {
   feedback: string
   email: string
   rumSessionId: string
+  radio: string
```
Comment (karrui) [inline shared/types/env.ts]: nit: should we name this something clearer? like `switchReason` or something

File: frontend/src/features/env/SwitchEnvFeedbackModal.tsx [hunk 4]
```diff
@@ -120,6 +150,126 @@ export const SwitchEnvFeedbackModal = ({
                 <FormControl>
                   <Input type="hidden" {...register('url')} value={url} />
                 </FormControl>
+                <FormControl isRequired={true} isInvalid={!isEmpty(errors)}>
```
Comment (karrui) [inline frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: structure seems a little off, this `FormControl` element wraps a single radio group field, but its validity is constrained by all errors. should we update it to only care about the errors it needs?

nit: also true props do not need a `true` assignment

```tsx
<FormControl isRequired isInvalid={!!errors.radio || !!errors[FEEDBACK_OTHERS_INPUT_NAME]}>
  ...
  // As such, only need to render appropriate messages
  <FormErrorMessage>
    {errors.radio?.message ?? errors[FEEDBACK_OTHERS_INPUT_NAME]?.message}
  </FormErrorMessage>
</FormControl>
```

**Review by karrui — APPROVED** [review]
lgtm with some changes (not requested, you can do if you want, since this is temporary)

File: frontend/src/features/env/SwitchEnvFeedbackModal.tsx (hunk 1 above)
Comment (wanlingt) [reply frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: > lgtm with some changes (not requested, you can do if you want, since this is temporary)

ok tq! made them anyway since they're quick ones

Comment (wanlingt) [reply frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: > nit: suggest something less likely to collide, maybe `react-feedback-others-input`?

https://github.com/opengovsg/FormSG/pull/5245/commits/215307aefcbc89beeab0ae70e456032cb73fc71f

File: shared/types/env.ts (hunk 3 above)
Comment (wanlingt) [reply shared/types/env.ts]: https://github.com/opengovsg/FormSG/pull/5245/commits/215307aefcbc89beeab0ae70e456032cb73fc71f

File: frontend/src/features/env/SwitchEnvFeedbackModal.tsx (hunk 2 above)
Comment (wanlingt) [reply frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: https://github.com/opengovsg/FormSG/pull/5245/commits/4677cfcaf59f9e1676da8bbd23e8a661d1cfc3fd

File: frontend/src/features/env/SwitchEnvFeedbackModal.tsx (hunk 4 above)
Comment (wanlingt) [reply frontend/src/features/env/SwitchEnvFeedbackModal.tsx]: https://github.com/opengovsg/FormSG/pull/5245/commits/215307aefcbc89beeab0ae70e456032cb73fc71f

also modified `FormErrorMessage` bc the error icon for the radio group was showing up even when an unrelated error was triggered (email input) https://github.com/opengovsg/FormSG/pull/5245/commits/641ec3a772d394181457b22f7260128d0f0769d4

**Comment by wanlingt** [comment]
T.T my bad i didn't squash and merge
