### PR TITLE
fix(v2): redesign edit attachment drawer bar

### LINKED ISSUE #4353: Attachment size graphic is not clear when attachment size is exceeded
The whole bar is yellow which doesn't tell the user anything, and the vertical grey line is hidden by the bar.

Screenshot 2022-07-26 at 6 31 41 PM

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
The edit attachment drawer bar does not display correctly in cases when the existing attachments already hit the attachment limit for the form.

Closes [#4353 ]

## Solution
- Retype `AttachmentStackedBar` component to avoid implicit precondition that values has at least two elements (as well as their roles).
- Addition of `trigger` to ensure that form errors appear identically to angular.

**Breaking Changes** 
- No - this PR is backwards compatible  

## Screenshots

https://user-images.githubusercontent.com/25571626/184340004-4cf8d880-886f-4b43-9e51-e22182da68fa.mov

### CODE REVIEW

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx [hunk 1]
```diff
@@ -28,65 +31,99 @@ const FilledTrack = (props: BoxProps) => {
...
+
+  const totalAttachmentSize = useMemo(
+    () => existingValues.reduce((sum, v) => sum + v, 0) + newValue,
+    [existingValues, newValue],
+  )
+
   const isOverQuota = useMemo(
-    () => !!values && max < values.reduce((sum, v) => sum + v, 0),
-    [max, values],
+    () => !!existingValues && max < totalAttachmentSize,
```
Comment (karrui) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx]: `!!existingValues` will always be true, since it is an array. this check may not be needed, or `existingValuesProp` used, or checking with `existingValues.length` instead?

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx [hunk 2]
```diff
@@ -28,65 +31,99 @@ const FilledTrack = (props: BoxProps) => {
...
-      `minmax(auto, ${valueToPercent(values?.[1] ?? 0, min, max)}%)`,
-    ].join(' ')
-  }, [max, min, values])
+    const gridTemplateColumns = existingValues.map(
+      (value) => `${valueToPercent(value, min, max)}%`,
+    )
+    if (newValue > 0)
+      gridTemplateColumns.push(
+        `minmax(auto, ${valueToPercent(newValue, min, max)}%)`,
+      )
```
Comment (karrui) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx]: nit: wrap with braces for readability?

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx]: hmm, you're right, this check probably not needed (since anyway we set the skeleton into a loading state when `existingValuesProp` is not provided). will get rid of it!

Comment (justynoh) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx]: removed in [270f849](https://github.com/opengovsg/FormSG/pull/4565/commits/270f849d96cc309b531c5688e1f0464de2f3ab91)

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx (hunk 2 above)
Comment (justynoh) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditAttachment/AttachmentStackedBar.tsx]: added in [270f849](https://github.com/opengovsg/FormSG/pull/4565/commits/270f849d96cc309b531c5688e1f0464de2f3ab91)

**Review by karrui — APPROVED** [review]
lgtm
