### PR TITLE
fix: update response limit error message for storage mode submissions

### LINKED ISSUE #1343: Update response limit error messages
When the response limit is reached, Storage mode shows submission error with no good recovery text, while Email mode shows the correct error message. Update Storage mode error message to Email mode message.

### PR DESCRIPTION
**Pull request by jia1**
Closes #1343 and #1914

### CODE REVIEW

File: src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts [hunk 1]
```diff
@@ -117,12 +117,12 @@ const submitEncryptModeForm: ControllerHandler<
...
       error: formPublicResult.error,
     })
-    const { statusCode } = mapRouteError(formPublicResult.error)
+    const { statusCode, errorMessage } = mapRouteError(formPublicResult.error)
     if (statusCode === StatusCodes.GONE) {
       return res.sendStatus(statusCode)
     } else {
       return res.status(statusCode).json({
-        message: form.inactiveMessage,
+        message: errorMessage || form.inactiveMessage,
```
Comment (karrui) [inline src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts:125]: I think we can remove the form.inactiveMessage part; there will always be an errorMessage

**Review by karrui — CHANGES_REQUESTED** [review]

**Review by karrui — APPROVED** [review]
