### PR TITLE
fix(deps): bump helmet from 3.23.1 to 4.1.0

### LINKED ISSUE #180: HelmetJS v4 migration
Internet standards are constantly evolving and so are security standards.

Build on dependabot's PR at https://github.com/opengovsg/FormSG/pull/160 and upgrade the HelmetJS dependency to v4.

The [migration guide](https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide) should be consulted.

### PR DESCRIPTION
**Pull request by shuli-ogp**
## Problem

Builds on #160 
Closes #180
Bumps helmet from 3.23.1 to 4.1.0.

**New dependencies**:

- `nocache` :  helmet.noCache is deprecated and was removed in helmet@4. Replace with `nocache` npm package.

## Tests

- [ ] Check that the following CSPs are present: defaultSrc, imgSrc, fontSrc, scriptSrc, connectSrc, frameSrc, objectSrc, styleSrc, formAction, upgradeInsecureRequests, reportUri
- [ ] imgSrc / connectSrc: check that image can be uploaded correctly for form
- [ ] fontSrc: check that SG government banner renders correctly
- [ ] scriptSrc / frameSrc / styleSrc: check that captcha works and is rendered correctly

### CODE REVIEW

File: src/loaders/express/helmet.ts [hunk 1]
```diff
@@ -73,10 +74,22 @@ const helmetMiddlewares = () => {
...
       formAction: ["'self'"],
-      upgradeInsecureRequests: !config.isDev,
-      reportUri: config.cspReportUri,
     },
-  })
+  }
+
+  // Add on upgradeInsecureRequest CSP header if !config.isDev
+  if (!config.isDev) {
+    set(cspDirectives, 'directives.upgradeInsecureRequests', [])
```
Comment (mantariksh) [inline src/loaders/express/helmet.ts:82]: tiny quibble: I would actually just do `cspDirectives.directives.upgradeInsecureRequests = []` here, and something similar for `cspReportUri`. We don't want these lines of code to fail silently if someone accidentally messes up the options.

**Review by mantariksh — APPROVED** [review]
lgtm, but roping in @arshadali172 for a review as well since this is clearly high-risk

File: src/loaders/express/helmet.ts [hunk 2]
```diff
@@ -24,7 +25,7 @@ const helmetMiddlewares = () => {
     policy: 'strict-origin-when-cross-origin',
   })
 
-  const contentSecurityPolicyMiddleware = helmet.contentSecurityPolicy({
+  let cspDirectives = {
```
Comment (mantariksh) [inline src/loaders/express/helmet.ts:28]: fun fact: you can (and should) declare objects and arrays as `const` even if you are going to modify them later. this is because even though you modify the object, the _reference_ which JavaScript holds to the object remains the same, so `const` is okay as long as you don't reassign the variable to something else:
```
const a = {}
a = { somethingElse: 'somethingElse' } // Uncaught TypeError: Assignment to constant variable.
```

File: src/loaders/express/helmet.ts (hunk 1 above)
Comment (shuli-ogp) [reply src/loaders/express/helmet.ts:82]: to clarify, you mean without the conditional if (!config.isDev)? or to not use lodash set

File: src/loaders/express/helmet.ts (hunk 2 above)
Comment (shuli-ogp) [reply src/loaders/express/helmet.ts]: thanks! good point - I edited accordingly

File: src/loaders/express/helmet.ts (hunk 1 above)
Comment (mantariksh) [reply src/loaders/express/helmet.ts:82]: as in I think it's better not to use lodash set

Comment (mantariksh) [inline src/loaders/express/helmet.ts:82]: could you add a note that an empty array still sets the upgrade-insecure-requests header? and that this key needs to be excluded in order for the header to be excluded (i.e. a falsey value doesn’t work)?

Comment (mantariksh) [reply src/loaders/express/helmet.ts:82]: also link to the helmet docs

Comment (shuli-ogp) [reply src/loaders/express/helmet.ts:87]: Added

Comment (mantariksh) [reply src/loaders/express/helmet.ts:87]: very nice

**Review by mantariksh — CHANGES_REQUESTED** [review]
as discussed on Slack, to use `@types/helmet` rather than object literals

**Comment by shuli-ogp** [comment]
@mantariksh changes made, for your re-review

File: src/loaders/express/helmet.ts (hunk 1 above)
Comment (shuli-ogp) [reply src/loaders/express/helmet.ts]: edited

File: src/loaders/express/helmet.ts [hunk 3]
```diff
@@ -24,7 +24,11 @@ const helmetMiddlewares = () => {
     policy: 'strict-origin-when-cross-origin',
   })
 
-  const contentSecurityPolicyMiddleware = helmet.contentSecurityPolicy({
+  //Declare type of cspDirective. Workaround to extract the type from helmet because
+  //@types/helmet is out of date and helmet doesn’t export those specific types
+  type cspDirective = Parameters<typeof helmet.contentSecurityPolicy>[0]
```
Comment (mantariksh) [inline src/loaders/express/helmet.ts:29]:
```suggestion
  type ICspDirectives = Parameters<typeof helmet.contentSecurityPolicy>[0]
```

File: src/loaders/express/helmet.ts [hunk 4]
```diff
@@ -24,7 +24,11 @@ const helmetMiddlewares = () => {
...
+
+  const cspDirectives: cspDirective = {
```
Comment (mantariksh) [inline src/loaders/express/helmet.ts:31]:
```suggestion
  const cspDirectives: ICspDirectives = {
```

**Review by mantariksh — APPROVED** [review]
minor quibbles about variable naming, other than that lgtm!

File: src/config/config.ts [hunk 5]
```diff
@@ -110,10 +110,8 @@ const submissionsTopUp = parseInt(process.env.SUBMISSIONS_TOP_UP, 10) || 0
 
 /**
  * Content Security Policy reporting
- * HelmetJS reportUri param requires non-empty string, so 'undefined' is
- * declared.
  */
-const cspReportUri = process.env.CSP_REPORT_URI || 'undefined'
```
Comment (arshadali172) [inline src/config/config.ts:116]: Might need to rebase and fix merge issues after https://github.com/opengovsg/FormSG/pull/190 is merged in

**Review by arshadali172 — APPROVED** [review]

**Comment by mantariksh** [comment]
@shuli-ogp yo, what's the status on this? are you making any more changes?

**Comment by shuli-ogp** [comment]
@mantariksh yup, sorting out the merge conflicts from #190 + writing tests to check the headers

**Comment by shuli-ogp** [comment]
@mantariksh @arshadali172 I've fixed merge conflicts and added on tests. Appreciate your re-review before I merge!

File: src/loaders/express/tests/helmet.spec.ts [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+describe('helmetMiddlewares', () => {
+  afterEach(() => {
+    jest.clearAllMocks()
+  })
+
+  it('should load the value of helmet.xssFilter()', () => {
+    jest.mock('helmet')
+    const mockHelmet = mocked(helmet, true)
+    mockHelmet.xssFilter = jest.fn().mockImplementation(() => 'xss')
+    const xssValue = helmetMiddlewares()[0]
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:18]: I'm not sure indexing into the return value of the module is the right approach. this makes the tests highly restrictive - future devs cannot even change the order of the function calls without breaking the tests, even if the code is perfectly functional. what's more important here is:
1. The functions are all called with the correct arguments. Look at the matchers `toHaveBeenCalled` and `toHaveBeenCalledWith`.
2. The return value of the module contains the expected outputs of all the functions that have been called. You can call the `helmetMiddleWares` function with all the `helmet` functions mocked, and expect the array returned to contain all your mocked return values.

**Review by mantariksh — CHANGES_REQUESTED** [review]

File: src/loaders/express/helmet.ts [hunk 7]
```diff
@@ -75,15 +81,21 @@ const helmetMiddlewares = () => {
...
   )
-  const cspOptionalDirectives = reportUri ? { reportUri } : {}
+
+  const cspOptionalDirectives: ICsp['directives'] = {}
+
+  // Add on reportUri CSP header if ReportUri exists
+  if (reportUri) cspOptionalDirectives.reportUri = [reportUri]
+
+  // Add on upgradeInsecureRequest CSP header if !config.isDev
+  if (!config.isDev) cspOptionalDirectives.upgradeInsecureRequests = []
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/helmet.ts:101]: yes, I had mistakenly left them out when resolving the merge conflicts

File: src/loaders/express/tests/helmet.spec.ts (hunk 6 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: thanks! this is useful guidance, see if the revised tests are ok

File: src/loaders/express/tests/helmet.spec.ts [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+  mockHelmet.contentSecurityPolicy = jest
+    .fn()
+    .mockImplementation((directiveObj) => JSON.stringify(directiveObj))
+  jest.mock('src/config/feature-manager')
+  const mockFeatureManager = mocked(featureManager, true)
+
+  mockFeatureManager.props = jest.fn().mockImplementation(() => {
+    return { cspReportUri: 'value' }
+  })
+  let contentSecurityPolicy = helmetMiddlewares()[7]
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: fixed

File: src/loaders/express/tests/helmet.spec.ts [hunk 9]
```diff
@@ -0,0 +1,139 @@
...
+  it('should load the value of helmet.xssFilter()', () => {
+    jest.mock('helmet')
+    const mockHelmet = mocked(helmet, true)
+    mockHelmet.xssFilter = jest.fn().mockImplementation(() => 'xss')
+    const xssValue = helmetMiddlewares()[0]
+    expect(xssValue).toEqual('xss')
+  })
+
+  it('should load the value of helmet.noSniff()', () => {
+    jest.mock('helmet')
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: fixed

File: src/loaders/express/tests/helmet.spec.ts [hunk 10]
```diff
@@ -0,0 +1,169 @@
...
+      .mockImplementation(() => 'dnsPrefetchControl')
+    mockHelmet.hidePoweredBy = jest
+      .fn()
+      .mockImplementation(() => 'hidePoweredBy')
+    mockHelmet.referrerPolicy = jest
+      .fn()
+      .mockImplementation(() => 'referrerPolicy')
+    mockHelmet.contentSecurityPolicy = jest
+      .fn()
+      .mockImplementation(() => 'contentSecurityPolicy')
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:32]: if you want all these mock implementations for all the tests, they shouldn't be lumped in the first test. since these constitute "setup" for all the tests, they should be in a `beforeAll` function. you should then run `jest.resetAllMocks()` in an `afterEach` block to ensure that the mocks get reset so function call history does not leak across tests.

File: src/loaders/express/tests/helmet.spec.ts [hunk 11]
```diff
@@ -0,0 +1,169 @@
...
+        "'sha256-b3IrgBVvuKx/Q3tmAi79fnf6AFClibrz/0S5x1ghdGU='",
+      ],
+      formAction: ["'self'"],
+    }
+    helmetMiddlewares()
+    expect(mockHelmet.contentSecurityPolicy).toHaveBeenCalledWith(
+      expect.objectContaining({
+        directives: expect.objectContaining({
+          ...cspCoreDirectives,
+        }),
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:100]: I'm wondering
(1) if we need to make this test stricter. shouldn't we expect the function to be called with exactly the object we want? might be better to declare the base object `cspCoreDirectives`, add `cspReportUri` and `upgradeInsecureRequests` as relevant, then expect the function to have been called with the exact object we expect.
(2) if we can make this test syntax less convoluted. perhaps (1) will solve that by itself

File: src/loaders/express/tests/helmet.spec.ts [hunk 12]
```diff
@@ -0,0 +1,169 @@
...
+      }),
+    )
+  })
+
+  it('should call helmet.contentSecurityPolicy() with the correct reportUri if cspReportUri', () => {
+    mockFeatureManager.props = jest.fn().mockImplementation(() => {
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:106]: you can also use `mockReturnValue` or `mockReturnValueOnce`

File: src/loaders/express/tests/helmet.spec.ts [hunk 13]
```diff
@@ -0,0 +1,169 @@
...
+          reportUri: ['value'],
+        }),
+      }),
+    )
+  })
+
+  it('should call helmet.contentSecurityPolicy() without a reportUri if !cspReportUri', () => {
+    mockFeatureManager.props = jest.fn().mockImplementation(() => {
+      return
+    })
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:122]: I don't think this is necessary. Doesn't the mock function return `undefined` by default if you don't specify a mock implementation?

**Review by mantariksh — CHANGES_REQUESTED** [review]

File: src/loaders/express/tests/helmet.spec.ts (hunk 10 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts:32]: should this be beforeEach instead of beforeAll? otherwise jest.resetAllMocks() in afterEach would clear it after the first test

File: src/loaders/express/tests/helmet.spec.ts (hunk 13 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: thanks! edited accordingly

File: src/loaders/express/tests/helmet.spec.ts (hunk 12 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: thanks! edited accordingly

File: src/loaders/express/tests/helmet.spec.ts (hunk 11 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: I've simplified the tests and made them stricter

File: src/loaders/express/helmet.ts [hunk 14]
```diff
@@ -77,15 +83,24 @@ const helmetMiddlewares = () => {
...
     undefined,
   )
-  const cspOptionalDirectives = reportUri ? { reportUri } : {}
+
+  const cspOptionalDirectives: ICsp['directives'] = {}
+
+  // Add on reportUri CSP header if ReportUri exists
+  // It is necessary to have the if statement for optional directives because falsey values
+  // do not work - e.g. cspOptionalDirectives.reportUri = [false] will still set the reportUri header
+  // See https://github.com/helmetjs/helmet/blob/cb170160e7c1ccac314cc19d3b979cfc771f1349/middlewares/content-security-policy/index.ts#L135
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/helmet.ts]: thanks! edited accordingly

File: src/loaders/express/tests/helmet.spec.ts (hunk 10 above)
Comment (mantariksh) [reply src/loaders/express/tests/helmet.spec.ts:32]: sry I meant `clearAllMocks`

File: src/loaders/express/tests/helmet.spec.ts [hunk 15]
```diff
@@ -0,0 +1,137 @@
...
+    expect(mockHelmet.xssFilter).toHaveBeenCalled()
+    expect(mockHelmet.noSniff).toHaveBeenCalled()
+    expect(mockHelmet.ieNoOpen).toHaveBeenCalled()
+    expect(mockHelmet.dnsPrefetchControl).toHaveBeenCalled()
+    expect(mockHelmet.hidePoweredBy).toHaveBeenCalled()
+    expect(mockHelmet.referrerPolicy).toHaveBeenCalled()
+    expect(mockHelmet.contentSecurityPolicy).toHaveBeenCalled()
+  })
+
+  const cspCoreDirectives = {
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:50]: nit: since this is a constant for the purposes of the tests, declare it at the top of the file

File: src/loaders/express/tests/helmet.spec.ts [hunk 16]
```diff
@@ -0,0 +1,137 @@
...
+
+  it('should call the correct helmet functions', () => {
+    helmetMiddlewares()
+    expect(mockHelmet.xssFilter).toHaveBeenCalled()
+    expect(mockHelmet.noSniff).toHaveBeenCalled()
+    expect(mockHelmet.ieNoOpen).toHaveBeenCalled()
+    expect(mockHelmet.dnsPrefetchControl).toHaveBeenCalled()
+    expect(mockHelmet.hidePoweredBy).toHaveBeenCalled()
+    expect(mockHelmet.referrerPolicy).toHaveBeenCalled()
+    expect(mockHelmet.contentSecurityPolicy).toHaveBeenCalled()
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:47]: should expect `helmet.hsts` to have been called with certain arguments as well right?

**Review by mantariksh — CHANGES_REQUESTED** [review]
minor nits remaining!

File: src/loaders/express/tests/helmet.spec.ts (hunk 16 above)
Comment (mantariksh) [reply src/loaders/express/tests/helmet.spec.ts:47]: or rather we need to ensure that `hstsMiddleware` behaves correctly. perhaps it should have its own separate unit test?

File: src/loaders/express/tests/helmet.spec.ts [hunk 17]
```diff
@@ -0,0 +1,137 @@
...
+describe('helmetMiddlewares', () => {
+  jest.mock('helmet')
+  const mockHelmet = mocked(helmet, true)
+  jest.mock('src/config/feature-manager')
+  const mockFeatureManager = mocked(featureManager, true)
+  jest.mock('src/config/config')
+  const mockConfig = mocked(config, true)
+
+  beforeEach(() => {
+    mockHelmet.xssFilter = jest.fn().mockImplementation(() => 'xssFilter')
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: Edited

File: src/loaders/express/tests/helmet.spec.ts [hunk 18]
```diff
@@ -0,0 +1,137 @@
...
+    mockHelmet.referrerPolicy = jest
+      .fn()
+      .mockImplementation(() => 'referrerPolicy')
+    mockHelmet.contentSecurityPolicy = jest
+      .fn()
+      .mockImplementation(() => 'contentSecurityPolicy')
+  })
+
+  afterEach(() => {
+    jest.resetAllMocks()
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: Edited

File: src/loaders/express/tests/helmet.spec.ts [hunk 19]
```diff
@@ -0,0 +1,137 @@
...
+
+describe('helmetMiddlewares', () => {
+  jest.mock('helmet')
+  const mockHelmet = mocked(helmet, true)
+  jest.mock('src/config/feature-manager')
+  const mockFeatureManager = mocked(featureManager, true)
+  jest.mock('src/config/config')
+  const mockConfig = mocked(config, true)
+
+  beforeEach(() => {
```
[the remark this answers is not in the document]
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: Edited

File: src/loaders/express/tests/helmet.spec.ts (hunk 15 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts:18]: Edited

File: src/loaders/express/tests/helmet.spec.ts (hunk 16 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: Added in the tests - see if ok

File: src/loaders/express/tests/helmet.spec.ts [hunk 20]
```diff
@@ -0,0 +1,162 @@
...
+    expect(mockHelmet.hidePoweredBy).toHaveBeenCalled()
+    expect(mockHelmet.referrerPolicy).toHaveBeenCalled()
+    expect(mockHelmet.contentSecurityPolicy).toHaveBeenCalled()
+  })
+
+  it('should call helmet.hsts() if req.secure', () => {
+    const mockReq = expressHandler.mockRequest({ secure: true })
+    const mockRes = expressHandler.mockResponse()
+
+    helmetMiddlewares().filter((result) => typeof result === 'function')[0](
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:106]:
```suggestion
    helmetMiddlewares().find((result) => typeof result === 'function')(
```

File: src/loaders/express/tests/helmet.spec.ts [hunk 21]
```diff
@@ -0,0 +1,162 @@
...
+      mockReq,
+      mockRes,
+      jest.fn(),
+    )
+    expect(mockHelmet.hsts).toHaveBeenCalled()
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:111]:
```suggestion
    expect(mockHelmet.hsts).toHaveBeenCalledWith({ maxAge: 5184000 })
```

File: src/loaders/express/tests/helmet.spec.ts [hunk 22]
```diff
@@ -0,0 +1,162 @@
...
+      .fn()
+      .mockReturnValue('dnsPrefetchControl')
+    mockHelmet.hidePoweredBy = jest.fn().mockReturnValue('hidePoweredBy')
+    mockHelmet.referrerPolicy = jest.fn().mockReturnValue('referrerPolicy')
+    mockHelmet.contentSecurityPolicy = jest
+      .fn()
+      .mockReturnValue('contentSecurityPolicy')
+    mockHelmet.hsts = jest
+      .fn()
+      .mockReturnValue(jest.fn().mockReturnValue('hsts'))
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:84]: the mock return value isn't necessary for hsts right?

File: src/loaders/express/tests/helmet.spec.ts [hunk 23]
```diff
@@ -0,0 +1,162 @@
...
+  it('should not call helmet.hsts() if !req.secure', () => {
+    const mockReq = expressHandler.mockRequest({ secure: false })
+    const mockRes = expressHandler.mockResponse()
+
+    helmetMiddlewares().filter((result) => typeof result === 'function')[0](
+      mockReq,
+      mockRes,
+      jest.fn(),
+    )
+    expect(mockHelmet.hsts).not.toHaveBeenCalled()
```
Comment (mantariksh) [inline src/loaders/express/tests/helmet.spec.ts:123]: I'd suggest setting a spy on `next` and making sure the spy gets called

File: tests/unit/backend/helpers/jest-express.ts [hunk 24]
```diff
@@ -4,15 +4,18 @@ const mockRequest = <P extends Record<string, string>, B>({
...
   params?: P
   body?: B
   session?: any
+  secure?: boolean
 } = {}) => {
   return {
     body: body ?? {},
     params: params ?? {},
     session: session ?? {},
+    secure: secure ?? {},
```
Comment (mantariksh) [inline tests/unit/backend/helpers/jest-express.ts:18]: the default value for secure shouldn't be an object right? this should be something like `secure ?? true`

**Review by mantariksh — CHANGES_REQUESTED** [review]
nearly there! just a few adjustments

File: src/loaders/express/tests/helmet.spec.ts (hunk 20 above)
Comment (mantariksh) [reply src/loaders/express/tests/helmet.spec.ts:106]: also probably good to add a comment explaining why this works (i.e. all other return values are mocked)

Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: edited as follows:

```
    // Find works for helmet.hsts() because the other functions are mocked to return a string
    const hstsFn = helmetMiddlewares().find(
      (result) => typeof result === 'function',
    )
    // Necessary to check for hstsFn because find() returns undefined by default, otherwise
    // will throw TypeError
    if (hstsFn) {
      hstsFn(mockReq, mockRes, mockNext)
    }
```

File: src/loaders/express/tests/helmet.spec.ts (hunk 22 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: removed

File: src/loaders/express/tests/helmet.spec.ts (hunk 23 above)
Comment (shuli-ogp) [reply src/loaders/express/tests/helmet.spec.ts]: edited

File: tests/unit/backend/helpers/jest-express.ts (hunk 24 above)
Comment (shuli-ogp) [reply tests/unit/backend/helpers/jest-express.ts]: edited

**Review by mantariksh — APPROVED** [review]
lgtm! thank you for your patience with all the feedback, and I'm glad that one of our most important modules is now well-tested!
