### PR TITLE
fix: return 404 for unmatched static assets

### LINKED ISSUE #5577: Catch-all router should still report 404s
The catch-all router serves the main react app (html content). This is too aggressive. In particular, requests for assets under `/static` that reach the catch-all handler should get 404 responses.

### PR DESCRIPTION
**Pull request by timotheeg**
## Problem
The catch-all handler we have for react (which is mostly used to catch all the admin routes) is hiding 404 responses because it always returns 200 with html content.

We know some users sometimes see blank pages and it's likely during release when there's a mismatch between static assets (old assets requested on new server, or new assets requested on old server).

fixes #5577 

Additional info: the reason we have a catch-all in react is to capture all the admins routes without having to list them explicitly in express. Listing all app routes (admins and respondent) rather than `*` would be an alternative solution, since then the final catcher would be the error handler, which would return 404 for all non-matched routes.

## Solution
This PR doesn't fix the problem (this will come in a separate process), but it restored our visibility into 404s for static assets.

Tested locally:
```bash
➜ curl -v http://localhost:5001/617acb2cf1180300148af690 2>&1 | grep '< HTTP'
< HTTP/1.1 200 OK

➜ curl -v http://localhost:5001/static/ 2>&1 | grep '< HTTP'
< HTTP/1.1 404 Not Found

➜ curl -v http://localhost:5001/static/foo 2>&1 | grep '< HTTP'
< HTTP/1.1 404 Not Found

➜ curl -v http://localhost:5001/foo.bar 2>&1 | grep '< HTTP'
< HTTP/1.1 404 Not Found

➜ curl -v http://localhost:5001/robots.txt 2>&1 | grep '< HTTP'
< HTTP/1.1 200 OK

➜ curl -v http://localhost:5001/static/js/1.e7cd9c85.chunk.js 2>&1 | grep '< HTTP'
< HTTP/1.1 200 OK

➜ curl -v http://localhost:5001/static/js/1.aaaaaaaa.chunk.js 2>&1 | grep '< HTTP'
< HTTP/1.1 404 Not Found
```

### CODE REVIEW

File: src/app/loaders/express/error-handler.ts [hunk 1]
```diff
@@ -22,6 +22,14 @@ const isHTTPLikeError = (
   return types.isNativeError(err) && 'statusCode' in err
 }
 
+// 404 since no middleware responded
+export const catchNonExistentRoutesMiddleware: RequestHandler = function (
```
Comment (mantariksh) [inline src/app/loaders/express/error-handler.ts]: ha, we probably missed this file while converting all functions to arrow functions. can fix another time

File: src/app/loaders/express/error-handler.ts [hunk 2]
```diff
@@ -115,14 +123,6 @@ const errorHandlerMiddlewares = (): (
...
-  // Assume 404 since no middleware responded
-  const catchNonExistentRoutesMiddleware: RequestHandler = function (
-    _req,
-    res,
-  ) {
-    res.sendStatus(StatusCodes.NOT_FOUND)
-  }
-
   return [genericErrorHandlerMiddleware, catchNonExistentRoutesMiddleware]
 }
```
Comment (mantariksh) [inline src/app/loaders/express/error-handler.ts:117]: tiny nit: in an ideal world I would remove line 129 and change `errorHandlerMiddlewares` to a named export just so it's clear what the difference is between the multiple exports from this file. but not a big deal

**Review by mantariksh — APPROVED** [review]
just to confirm, the browser behaviour will be the same right? users will still see a blank page, just that this time it's because we're serving a 404 instead of html

File: src/app/loaders/express/index.ts [hunk 3]
```diff
@@ -131,10 +133,19 @@ const loadExpressApp = async (connection: Connection) => {
   // New routes in preparation for API refactor.
   app.use('/api', ApiRouter)
 
+  // serve static assets
```
Comment (tshuli) [inline src/app/loaders/express/index.ts]:
```suggestion
  // serve static assets. `dist/frontend` contains the root files as well as a `/static` folder
  // express.static calls next() if the file is not found
```

Comment (tshuli) [reply src/app/loaders/express/index.ts]: suggested documentation for future devs

File: src/app/loaders/express/index.ts [hunk 4]
```diff
@@ -131,10 +133,19 @@ const loadExpressApp = async (connection: Connection) => {
...
   app.use('/public', express.static(path.resolve('dist/angularjs')))
-  app.get('/old/', HomeController.home)
 
+  // Requests for known static asset patterns which were not served by
+  // the static handlers above should return 404s
+  app.get(/^\/(public|static)\//, catchNonExistentRoutesMiddleware)
+
+  // Requests for root files (e.g. /robots.txt or /favicon.ico) that were
+  // not served statically above will also return 404
+  app.get(/^\/[^/]+\.[a-z]{2,}$/, catchNonExistentRoutesMiddleware)
```
Comment (tshuli) [inline src/app/loaders/express/index.ts]: No objections per se but just wondering why we need to be so specific with the filename format - are there no legitimate cases in future where we could have:
- filename with no extension
- filename with single-character extension

**Review by tshuli — APPROVED** [review]
lgtm, with just some minor comments!

**Comment by timotheeg** [comment]
> just to confirm, the browser behaviour will be the same right? users will still see a blank page, just that this time it's because we're serving a 404 instead of html

Correct! This PR is not a functional fix from the user perspective, it's an observability fix for us to have visibility on errors.

File: src/app/loaders/express/index.ts (hunk 4 above)
Comment (timotheeg) [reply src/app/loaders/express/index.ts]: Aye, I wanted to capture files with dots specifically `{name}.{extension}` so I wouldn't risk matching forms with urls `/{formid}` (those are not meant to be served statically, but also should not be 404s).

I can drop the extension specificity though, this is indeed not useful!

File: src/app/loaders/express/error-handler.ts (hunk 2 above)
Comment (timotheeg) [reply src/app/loaders/express/error-handler.ts:117]: I'll do it!

Comment (timotheeg) [reply src/app/loaders/express/error-handler.ts:117]: I wonder why the 2 handlers in `errorHandlerMiddlewares` were defined as local functions btw I'll convert them both to module functions for consistency.

Comment (timotheeg) [reply src/app/loaders/express/error-handler.ts:117]: Done in https://github.com/opengovsg/FormSG/pull/5579/commits/5cc48bfe3cd4f037fab3ff12a7893e07656805d4

File: src/app/loaders/express/index.ts (hunk 4 above)
Comment (timotheeg) [reply src/app/loaders/express/index.ts]: Done in https://github.com/opengovsg/FormSG/pull/5579/commits/bbd5ab5d0c7c76bc79d6889f0df430988c88ae51

File: src/app/loaders/express/error-handler.ts (hunk 1 above)
Comment (timotheeg) [reply src/app/loaders/express/error-handler.ts]: Fixed in https://github.com/opengovsg/FormSG/pull/5579/commits/5cc48bfe3cd4f037fab3ff12a7893e07656805d4 too
