### PR TITLE
fix: make email validation insensitive to domains case and trailing whitespace

### LINKED ISSUE #5557: Restrict email domain should not be case sensitive
image

E.g from picture: Admin has restricted the email field to @open.gov.sg domain. However, if you capitalise any of the letters, it will count as invalid.

### PR DESCRIPTION
**Pull request by foochifa**
## Problem

Closes [#5557]

## Solution

Trim whitespace and lower case domain value before comparison with allowedDomains.

**Breaking Changes** 

- No - this PR is backwards compatible  

## Before & After Screenshots

**BEFORE**:

image

**AFTER**:

image

## Tests

- [ ] Create a form with an email field. Enable 'Restrict Email Domains'. Arbitrarily fill in 'Domains allowed' (e.g. @data.gov.sg). Open/Activate form. Access the form and input an email account (with allowed domain) with **capitalisation in the domain name** (e.g. bob@DATA.gov.sg), email should be verifiable.
- [ ] Create a form with an email field. Enable 'Restrict Email Domains'. Arbitrarily fill in 'Domains allowed' (e.g. @data.gov.sg). Open/Activate form. Access the form and input an email account (with allowed domain) with **preceding or trailing whitespaces**, email should be verifiable.

### CODE REVIEW

**Review by karrui — APPROVED** [review]
lgtm

File: frontend/src/utils/fieldValidation.ts [hunk 1]
```diff
@@ -479,7 +479,7 @@ export const baseEmailValidationFn =
       ? new Set(schema.allowedEmailDomains)
       : new Set()
     if (allowedDomains.size !== 0) {
-      const domainInValue = inputValue.split('@')[1]
+      const domainInValue = inputValue.split('@')[1].toLowerCase()
```
Comment (karrui) [inline frontend/src/utils/fieldValidation.ts]: might want to trim also

**Review by karrui — APPROVED** [review]
