### PR TITLE
fix(a11y/windows): read out question text when using Tab to navigate

### LINKED ISSUE #5588: a11y: question text is not read out when using Tab to navigate (Windows)
**Issue**
When the user uses the Tab key to navigate from one form element to another, the question text does not get read out for some questions, and only the question options gets read out. This issue does not appear when using the arrow keys to navigate instead.

This issue affects questions 8, 10, and 12.

i.e. The affected form questions are the following:

- 1 to 5 star rating
- Yes/No buttons
- File upload

**Suggestion by Etch**
The issue seems to be caused by the ARIA labels in the options for the affected questions taking precedence over the ARIA label in the question text.

For form questions of this nature, one potential fix for this issue is to place the radiogroup inside a <fieldset> tag.

Then, place the question text inside a <legend> tag above the radiogroup.

This would fix the ARIA labels to read the question text and question options properly using the Tab key for navigation.

Additionally, for the Yes/No button question type (i.e. Question 10), the role="button" in the <label> tag needs to be removed for this implementation to work.

This has the added benefit of making the input type detected as radio buttons to screen readers, as it currently only is detected as a selectable button, which means keyboard shortcuts to jump to radio buttons using screen readers do not work for Question 10.

**Screenshot**
https://drive.google.com/file/d/1iqMyET-YQg9jNFZzUkXYqVSGJ4IjME0n/view?usp=share_link

### PR DESCRIPTION
**Pull request by LinHuiqing**
## Problem

On Windows devices, when the Tab key is used for navigation, the question texts for the following question types are not read out:

- Yes/no
- Attachment
- Rating (addressed in PR #5767)

Refer to issue #5588 for more details.

Closes #5588

## Solution

As Tab key reads out information for options directly, pass the question text into the options to be read out as aria-labels.

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

**Bug Fixes**:

- Questions will now be read out for Yes/no and Attachment fields

## Before & After Screenshots

**BEFORE**:

https://user-images.githubusercontent.com/37061143/218991896-f1b8c510-7191-4de3-90f1-ad39a631ab5c.mp4

**AFTER**:

https://user-images.githubusercontent.com/37061143/218986659-6f9dbc3e-8bcf-4ee9-aa3e-c229e2d3501b.mp4

## Tests

- [ ] Using Windows' NVDA software, use Tab navigation to get around in a form with Yes/no and Attachment fields. 
- [ ] You should be able to hear the question text for Yes/no fields now.
- [ ] You should be able to hear the question text for Attachment fields now.

### CODE REVIEW

File: frontend/src/components/Field/Attachment/AttachmentDropzone.tsx [hunk 1]
```diff
@@ -8,19 +8,21 @@ interface AttachmentDropzoneProps {
...
   readableMaxSize,
+  question,
 }: AttachmentDropzoneProps): JSX.Element => {
   const styles = useStyles()
 
   return (
     <>
       <VisuallyHidden>
-        Click to upload file, maximum file size of {readableMaxSize}
+        {question} Click to upload file, maximum file size of {readableMaxSize}
```
Comment (foochifa) [inline frontend/src/components/Field/Attachment/AttachmentDropzone.tsx:25]: Is there a reason why we put the question here over including it as an aria-label in the chakra.input below?

Comment (LinHuiqing) [reply frontend/src/components/Field/Attachment/AttachmentDropzone.tsx:25]: Oh, because:
1. The question should come before what the user should do.
2. I kind of assumed this was a better place to put it as VisuallyHidden is intended for screen readers and previous engineers chose to. 

Anyways, I tried it out with the following snippet:
```ts
<chakra.input
  aria-label={`${question} Click to upload file, maximum file size of ${readableMaxSize}`}
  {...inputProps}
  data-testid={inputProps.name}
/>
```

On windows, this will just read "button required" as seen in the video below:

https://user-images.githubusercontent.com/37061143/219065430-3e9b504d-0077-4c6c-bea4-aed94ed96e97.mp4

So this probably means NVDA does not pick up the `aria-label` of `chakra.input`. Thus, I'm guessing `VisuallyHidden` was used (by @justynoh I think) for screen readers to pick up and give more informative descriptions to our visually impaired users.

Relatedly, I just read [this article](https://gomakethings.com/revisting-aria-label-versus-a-visually-hidden-class/) that points out the flaws of `aria-label`s and explains when to use `VisuallyHidden` elements.

Comment (foochifa) [reply frontend/src/components/Field/Attachment/AttachmentDropzone.tsx:25]: Oh nice! Thanks I realised that aria-labels also don't work as expected all the time hahaha, maybe it has to do with assigning a role to the input or perhaps another option would be to envelop the input+icon field with a label container like in radio & Yes/No.

But seems like visually hidden works well here!

**Comment by foochifa** [comment]
lgtm!

**Review by foochifa — APPROVED** [review]

**Comment by foochifa** [comment]
Yikes wait sorry, could you edit the PR and change the test to be checkboxes, also separate the test for both Yes/No and attachment fields thanks!

**Comment by LinHuiqing** [comment]
Okays done!
