### PR TITLE
fix: update builder drawer design

### LINKED ISSUE #5016: Remove sections from fields and rearrage field icons.
All the fileds inside builder will be part of a single list. i.e. No sections such as 'Field' or 'Page'.

Design link for copy and icons arrangement: https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=2278%3A56352

### PR DESCRIPTION
**Pull request by wanlingt**
## Solution

The builder drawer has been redesigned. This PR
- rearranges the fields
- removes 'Page' and 'Field' sections from the drawer

Additionally, `FieldSection`'s `label` prop is now optional.

Closes #5016

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

## Tests

- [x] Drag and drop a field that was previously under the 'Page' section. Field should appear in the builder, in preview and in the public form.
- [x] Repeat the same for a field that was previously under the 'Field' section. Field should appear in the builder, in preview and in the public form.
- [x] Repeat the same 2 tests above, but instead of drag and drop, click the field. Field should appear in the builder, in preview and in the public form.

### CODE REVIEW

**Comment by karrui** [comment]
may need to rebase/recommit for CI/CD to work properly 🙏

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx [hunk 1]
```diff
@@ -88,37 +86,20 @@ const BasicFieldPanelContent = () => {
 
   return (
     <>
```
Comment (karrui) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx]: this fragment is probably not needed anymore since there is only a single section now

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx [hunk 2]
```diff
@@ -275,7 +256,7 @@ const FieldSection = ({
   label,
   children,
 }: {
-  label: string
+  label?: string
```
Comment (karrui) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx:257]: now that this label can be undefined, we might want to update the `FieldSection` component to not render any `Text` components if not provided.

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx (hunk 1 above)
Comment (wanlingt) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx]: [edd1d33](https://github.com/opengovsg/FormSG/pull/5065/commits/edd1d334c5bdec7bfba435cc082315142ae765b1)

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx (hunk 2 above)
Comment (wanlingt) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx:257]: [31a87a6](https://github.com/opengovsg/FormSG/pull/5065/commits/31a87a632a9e72a15c882c11a22c97c475830c2d)

Comment (justynoh) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx:257]: actually if we aren't going to differentiate, maybe we can just get rid of `FieldSection` completely lol

**Review by justynoh — APPROVED** [review]
lgtm

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx (hunk 2 above)
Comment (wanlingt) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListDrawer.tsx:257]: it's still being used in the MyInfo panel, so wont get rid of it yet haha
