### PR TITLE
fix(a11y): start page, inline message and public switch message

### LINKED ISSUE #4180: a11y(navigation): header banner should be wrapped with a header tag

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
Form start page needs some a11y improvement.

Closes #4180

## Solution
add better `logoImgAlt`, remove screen reading for `X estimated time time to complete` icon, improve `InlineMessage` a11y

**Breaking Changes** 
- No - this PR is backwards compatible  

## Screenshots

https://user-images.githubusercontent.com/25571626/189843733-4efe415a-396e-4869-bc78-5be166eb7564.mov

### CODE REVIEW

File: frontend/src/features/public-form/components/PublicSwitchEnvMessage.tsx [hunk 1]
```diff
@@ -16,9 +16,19 @@ export const PublicSwitchEnvMessage = (): JSX.Element => {
...
-            <Button variant="link" onClick={onOpen}>
+            <span aria-hidden>
+              You’re using the new FormSG design. If you have trouble
+              submitting,
+            </span>
+            <Button
+              variant="link"
+              onClick={onOpen}
+              aria-label="You're using the new FormSG design. If you have trouble submitting, switch to the original one here."
+            >
```
Comment (wanlingt) [inline frontend/src/features/public-form/components/PublicSwitchEnvMessage.tsx]:
```suggestion
          <HStack spacing="0px">
            <Text aria-hidden>
              You’re using the new FormSG design. If you have trouble
              submitting,
            </Text>
            <Button
              variant="link"
              onClick={onOpen}
              aria-label="You're using the new FormSG design. If you have trouble submitting, switch to the original one here."
            >
              <Text as="u">switch to the original one here.</Text>
            </Button>
          </HStack>
```

To keep it standardised should we stick to using Chakra instead of `span`? Don't think we have `span` anywhere else in the react app

**Review by wanlingt — APPROVED** [review]
lgtm!
