### PR TITLE
fix(form-v2): add loading state for form builder, misc improvements

### LINKED ISSUE #4371: Builder should have loading state
When builder is loading, it appears like there are no form fields

### PR DESCRIPTION
**Pull request by karrui**
> Supersedes #4461

## Problem
Currently, the loading state for the form builder displays the empty form placeholder. This PR adds a proper loading screen for the form.

This PR also reduces mobile padding to increase usability. 
Also a bunch of fixes for Admin Form Builder.

**Actually** closes #4371 

## Solution

**Breaking Changes** 
- [X] No - this PR is backwards compatible  

**Features**:

- feat(FormBuilder): add loading skeleton

**Improvements**:

- fix(StartPageView): show unauthed FormHeader by default
- feat: expose form loading state to admin form builder context
- feat: update responsive margins and paddings 
- feat: disable create field drag in mobile view 

## Before & After Screenshots
Should be updated

### CODE REVIEW

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListOption.tsx [hunk 1]
```diff
@@ -69,38 +71,42 @@ export const DraggableBasicFieldListOption = ({
...
-            ref={provided.innerRef}
-          />
-          {snapshot.isDragging && (
+}: DraggableBasicFieldOptionProps): JSX.Element => {
+  const isMobile = useIsMobile()
+
+  return (
+    <Draggable
+      index={index}
+      isDragDisabled={isDisabled || isMobile}
```
Comment (justynoh) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/FieldListDrawer/FieldListOption.tsx:80]: we could potentially also implement on drag = close builder drawer for mobile to enable this feature but maybe after react :P

**Review by justynoh — APPROVED** [review]

**Review by timotheeg — APPROVED** [review]
