### PR TITLE
fix: add auto-trimming for NRIC field

### LINKED ISSUE #5854: NRIC field does not auto correct leading/trailing whitespaces
**Describe the bug**
Another regression in the React App (works in Angular) - if the form filler inputs an NRIC with whitespaces into the NRIC field, they are unable to submit their form

**Expected behavior**
NRIC field should auto trim leading/trailing whitespaces

**Additional Context**
Also mentioned in https://github.com/opengovsg/FormSG/issues/5655#issuecomment-1367152964

### PR DESCRIPTION
**Pull request by KenLSM**
## Problem

Spaces could be unintentionally included by the user when they are entering their NRIC. This can be incredibly frustrating for the user to identify why their NRIC had failed the validation. This is a regression issue arising from the react-angular migration.

Closes #5854

## Solution

We can remove one potential source of frustration through the inclusion of trimming the NRIC as there are no need for trailing/leading spaces.

**Breaking Changes** 

- [X] No - this PR is backwards compatible  

## Before & After Screenshots

**BEFORE**:

Screenshot 2023-02-28 at 7 17 20 PM

**AFTER**:
Screenshot 2023-02-28 at 6 57 29 PM

## Tests

- [ ] go to a form with an NRIC input. Attempt to enter a valid NRIC. It should pass validation without any error message appearing.
- [ ] go to a form with an NRIC input. Attempt to enter a valid NRIC with trailing or leading spaces. The input should not be updating with spaces present. It should pass validation without any error message appearing.

### CODE REVIEW

File: frontend/src/templates/Field/Nric/NricField.tsx [hunk 1]
```diff
@@ -28,7 +29,12 @@ export const NricField = ({ schema }: NricFieldProps): JSX.Element => {
         aria-label={`${schema.questionNumber}. ${schema.title}`}
         defaultValue=""
```
Comment (timotheeg) [inline frontend/src/templates/Field/Nric/NricField.tsx:29]: Is `defaultValue=""` still needed now that we pass a value in explicitly?

File: frontend/src/templates/Field/Nric/NricField.tsx [hunk 2]
```diff
@@ -28,7 +29,12 @@ export const NricField = ({ schema }: NricFieldProps): JSX.Element => {
...
         preventDefaultOnEnter
-        {...register(schema._id, validationRules)}
+        value={value}
+        {...register(schema._id, {
+          ...validationRules,
+          onChange: (event: React.ChangeEvent<HTMLInputElement>) =>
+            setValue(event.target.value.trim()),
+        })}
```
Comment (timotheeg) [inline frontend/src/templates/Field/Nric/NricField.tsx]: So just to confirm the render flow: if a user inputs a leading/trailing space, [validation](https://github.com/opengovsg/FormSG/blob/0f211f486f06c57a3d898dcb136eeb38cd38df7b/frontend/src/utils/fieldValidation.ts#L321-L339) will fail, but `onChange()` will fire and correct the input, validation will run again, and it will pass, and the user will not see any error message flash, correct?

File: frontend/src/templates/Field/Nric/NricField.test.tsx [hunk 3]
```diff
@@ -8,6 +8,9 @@ import * as stories from './NricField.stories'
 
 const { ValidationRequired, ValidationOptional } = composeStories(stories)
 
+const VALID_NRIC = 'S0000002G'
+const INVALID_NRIC = 'S0000001B'
```
Comment (timotheeg) [inline frontend/src/templates/Field/Nric/NricField.test.tsx:12]: 👍 👏

**Review by timotheeg — APPROVED** [review]

File: frontend/src/templates/Field/Nric/NricField.tsx (hunk 2 above)
Comment (KenLSM) [reply frontend/src/templates/Field/Nric/NricField.tsx]: Yes to `user will not see any error message flash`.  The flow works as expected for users that is correcting their input, but will fail when user had explicitly added a space. But to be pedantic, it will be called with the data that the user had input as opposed to the output of `setState`.

The reason for why this happens is due to the fact that `react-hooks-form` operates on uncontrolled component, and my initial implementation is turning the component into a controlled component, which breaks the assumption that `react-hooks-form` had.

The correct way to manipulate the form data is to use `setValue` hook provided by the form's context.

File: frontend/src/templates/Field/Nric/NricField.tsx (hunk 1 above)
Comment (KenLSM) [reply frontend/src/templates/Field/Nric/NricField.tsx:29]: Have added a switch to the implementation which now requires the use of the `defaultValue` field.

File: frontend/src/templates/Field/Nric/NricField.tsx (hunk 2 above)
Comment (timotheeg) [reply frontend/src/templates/Field/Nric/NricField.tsx]: Thanks for the explanation!

**Review by timotheeg — APPROVED** [review]
LGTM
