### PR TITLE
fix: align joi validation types to schema

### LINKED ISSUE #1810: LogicDto is typed incorrectly
In `src/types/form_logic.ts`, `LogicDto` is typed as

```
LogicDto = ConditionalPick<LeanDocument<ILogicSchema>, Primitive>
```

This was initially typed to be in line with `FormFieldDto`, but this is wrong because Logic contains nested objects which are not primitives, resulting in `LogicDto` only containing `_id` and `logicType`.

### PR DESCRIPTION
**Pull request by tshuli**
## Problem

- This PR builds off #1695 and replaces the typings for joi validation for logic endpoint to align to the schema
- Also closes #1810

### CODE REVIEW

File: src/app/modules/form/admin-form/admin-form.controller.ts [hunk 1]
```diff
@@ -1806,9 +1808,11 @@ export const handleUpdateLogic = [
           .items(
             Joi.object({
               field: Joi.string().required(),
-              state: Joi.string().required(),
-              value: Joi.string().required(),
-              ifValueType: Joi.string(),
+              state: Joi.string()
+                .valid(...Object.values(LogicConditionState))
+                .required(),
+              value: Joi.any().required(),
```
Comment (mantariksh) [inline src/app/modules/form/admin-form/admin-form.controller.ts:1814]: can I check why this is `any`? would it be possible to experiment with the various logic field types to determine exactly what type is being returned here? imo we should always know the exact shape of our APIs

File: src/app/modules/form/admin-form/admin-form.controller.ts [hunk 2]
```diff
@@ -1818,7 +1822,7 @@ export const handleUpdateLogic = [
         }),
         preventSubmitMessage: Joi.alternatives().conditional('logicType', {
           is: LogicType.PreventSubmit,
-          then: Joi.string().required(),
+          then: Joi.string(),
```
Comment (mantariksh) [inline src/app/modules/form/admin-form/admin-form.controller.ts:1825]: can I check why this is not `required`?

File: src/app/modules/form/admin-form/admin-form.controller.ts (hunk 1 above)
Comment (tshuli) [reply src/app/modules/form/admin-form/admin-form.controller.ts]: Thanks! I typed this based on the schema in `form_logic.server.schema.ts`. From what I can see though, it's either a number or string, so I've tightened accordingly. I also left open the possibility for it to be a number array or string array because we allow for those types in `src/types/form_logic.ts`

```
export interface ICondition {
  field: IFieldSchema['_id']
  state: LogicConditionState
  value: string | number | string[] | number[]
  ifValueType?: LogicIfValue
}
```

File: src/app/modules/form/admin-form/admin-form.controller.ts (hunk 2 above)
Comment (tshuli) [reply src/app/modules/form/admin-form/admin-form.controller.ts]: As above, it was to align with the schema, but I've tightened since we do require this on the frontend

**Comment by tshuli** [comment]
@mantariksh thanks for reviewing, for your re-review pls

File: src/app/modules/form/admin-form/admin-form.controller.ts [hunk 3]
```diff
@@ -1806,9 +1808,18 @@ export const handleUpdateLogic = [
...
+                .required(),
+              value: Joi.alternatives()
+                .try(
+                  Joi.number(),
+                  Joi.string(),
+                  Joi.array().items(Joi.string()),
+                  Joi.array().items(Joi.number()),
+                )
+                .required(),
+              ifValueType: Joi.valid(...Object.values(LogicIfValue)),
```
Comment (mantariksh) [inline src/app/modules/form/admin-form/admin-form.controller.ts:1822]: can I check why this is not required, and should it be? also is the behaviour different if you exclude `Joi.string()`, as in the `state` key?

File: src/types/form_logic.ts [hunk 4]
```diff
@@ -116,4 +111,4 @@ export type LogicCondition =
 /**
  * Logic POJO with functions removed
  */
-export type LogicDto = ConditionalPick<LeanDocument<ILogicSchema>, Primitive>
+export type LogicDto = ILogic & { _id?: IFieldSchema['_id'][] }
```
Comment (mantariksh) [inline src/types/form_logic.ts:114]: not that it makes a big difference, but why `IFieldSchema['_id']` instead of `ILogicSchema['_id']`?

Comment (tshuli) [reply src/types/form_logic.ts:114]: thanks! Actually I think the most correct one should be `Document['_id']`, since that is where all the Schemas inherit the `_id` property from

File: src/app/modules/form/admin-form/admin-form.controller.ts (hunk 3 above)
Comment (tshuli) [reply src/app/modules/form/admin-form/admin-form.controller.ts]: thanks, made it required. Excluding `string()` shouldn't make a difference because all the values in LogicIfValue are strings, but I think adding `string()` is more [canonical](https://joi.dev/api/?v=17.4.0#anyvalidvalues---aliases-equal). Edited accordingly

**Comment by tshuli** [comment]
@mantariksh thanks for reviewing, for your re-review pls
