### PR TITLE
fix: add frontend validation for duplicate Others

### LINKED ISSUE #5315: disallow duplicate 'others'
**Describe the bug**
We should not allow duplicate 'Others'

image

### PR DESCRIPTION
**Pull request by justynoh**
## Problem

Closes #5315

## Solution
Add frontend validation to ensure that there is no "Others" option in radio and checkbox options, if the others toggle is already on.

**Breaking changes**
- No - this PR is backwards compatible  

## Tests
For both radio and checkbox:
- [ ] New field should be addable if there is "Others" toggled.
- [ ] New field should be addable if there is manual "Others".
- [ ] New field should not be addable if there is both "Others" toggled and manual "Others".
- [ ] Existing field should not be updatable if there is both "Others" toggled and manual "Others".

### CODE REVIEW

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditCheckbox/EditCheckbox.tsx [hunk 1]
```diff
@@ -103,6 +104,17 @@ export const EditCheckbox = ({ field }: EditCheckboxProps): JSX.Element => {
 
   const watchedInputs = watch()
 
+  const optionsValidation = useCallback(
+    (opts: string) => {
+      const textareaValidation = SPLIT_TEXTAREA_VALIDATION.validate(opts)
+      if (textareaValidation !== true) return textareaValidation
```
Comment (wanlingt) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditCheckbox/EditCheckbox.tsx:111]:
```suggestion
      if (!textareaValidation) return textareaValidation
```

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditRadio/EditRadio.tsx [hunk 2]
```diff
@@ -75,6 +77,16 @@ export const EditRadio = ({ field }: EditRadioProps): JSX.Element => {
     [],
   )
 
+  const hasRadio = watch('othersRadioButton')
+  const optionsValidation = useCallback(
+    (opts: string) => {
+      const textareaValidation = SPLIT_TEXTAREA_VALIDATION.validate(opts)
+      if (textareaValidation !== true) return textareaValidation
```
Comment (wanlingt) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditRadio/EditRadio.tsx:85]:
```suggestion
      if (!textareaValidation) return textareaValidation
```

**Review by wanlingt — APPROVED** [review]

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditCheckbox/EditCheckbox.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditCheckbox/EditCheckbox.tsx:111]: added comment for clarification in [36b7ef3](https://github.com/opengovsg/FormSG/pull/5319/commits/36b7ef397d0882ba7c4ed6a553aced701e8b4b00) !
