### PR TITLE
fix: updates to thank you page

### LINKED ISSUE #5062: End page is not centered in the window
image

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
v6.2.1? hehe

Closes #5062, #5122

## Solution

**Breaking Changes** 

- No - this PR is backwards compatible

### CODE REVIEW

File: frontend/src/features/public-form/components/SectionSidebar/SectionSidebar.tsx [hunk 1]
```diff
@@ -89,11 +90,7 @@ export const SectionSidebar = (): JSX.Element => {
     )
 
   return submissionData ? (
-    <Box
-      flex={1}
-      d={{ base: 'none', md: 'initial' }}
-      minW={sectionScrollData.length > 0 ? '20%' : undefined}
-    ></Box>
+    <Spacer />
```
Comment (karrui) [inline frontend/src/features/public-form/components/SectionSidebar/SectionSidebar.tsx:93]: will this work properly in all viewports? trust you ah

**Review by karrui — APPROVED** [review]

File: frontend/src/features/public-form/components/SectionSidebar/SectionSidebar.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/features/public-form/components/SectionSidebar/SectionSidebar.tsx:93]: tested liao, the previous was bad cuz it forced 20% on smaller viewports which is wrong

Comment (justynoh) [reply frontend/src/features/public-form/components/SectionSidebar/SectionSidebar.tsx:93]: #5062
