### PR TITLE
fix(v2): allow maximum rows for table fields to be optional

### LINKED ISSUE #4935: [1] Table field maximum rows is required in react when it's optional in angular
Expected behaviour: maximum rows is optional
If no max rows specified, then considered as unlimited

image

### PR DESCRIPTION
**Pull request by justynoh**
## Problem
Previous version of the app allows users to not add a maximum number of rows, resulting in unlimited rows being able to be added. React did not have this feature.

Closes #4935 

## Solution
Remove requiredness for max rows in edit table, update associated components and handlers to manage this possibility.

**Breaking Changes** 
- No - this PR is backwards compatible  

## Screenshots

Admin form

https://user-images.githubusercontent.com/25571626/192338613-67a3c3e3-0568-457e-ba64-fa43038132c6.mov

Public form

https://user-images.githubusercontent.com/25571626/192338633-d2f6ca7f-46ea-413f-9def-4cfe5a18050c.mov

### CODE REVIEW

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditTable/EditTable.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ const transformTableFieldToEditForm = (
 
   return {
     ...pick(field, EDIT_TABLE_FIELD_KEYS),
```
Comment (karrui) [inline frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditTable/EditTable.tsx:62]: should we update the `EDIT_TABLE_FIELD_KEYS` constant instead to include the `addMoreRows` prop?

**Review by karrui — APPROVED** [review]
lgtm

**Review by wanlingt — APPROVED** [review]

File: frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditTable/EditTable.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/features/admin-form/create/builder-and-design/BuilderAndDesignDrawer/EditFieldDrawer/edit-fieldtype/EditTable/EditTable.tsx:62]: oops yes, `EDIT_TABLE_FIELD_KEYS` already actually contains `addMoreRows`. Don't code at 1:30am, people

fixed in [7c7c3b4](https://github.com/opengovsg/FormSG/pull/4945/commits/7c7c3b40971f048c7a4810f1476589c85da8619e)
