### PR TITLE
fix(a11y): move aria required and invalid from individual rating options to rating group

### LINKED ISSUE #5503: a11y: Rating reads as Unticked even when ticked
**Checked**
- Mac Voiceover reads Required Selected Invalid Data even when selected
- iPhone Voiceover whether it is selected or not, it reads unticked, reads 'Radio button unticked, 4 of 5 required' when selected 'Radio button unticked, 3 of 5 required'
- Talkback reads Option xx Ticked/Unticked Option 2 of 5 Radio Button

**Proposal**
- Could we [implement the scale](https://www.figma.com/file/9oE4ECjdeZQ1RBpwZVtnB3/Form-Design-Master?node-id=14439%3A138843&t=cNKitpnP9oUFpWBf-4)? And can we read out the scale before the stars, even though the placement is the other way around?
- On MacOS Voiceover, when it's selected, can we not read out Invalid data on Voiceover?
- On iOS Voiceover, can we read out what the user selects when selected? (e.g. selected, 2 of 5)

### PR DESCRIPTION
**Pull request by foochifa**
## Problem

Currently every individual rating option are tagged as aria-required and aria-invalid, which results in Mac Voiceover reading it as 'required selected invalid data'. 

Additionally, the labels of the rating option are not informative and aria labels should be implemented to describe how the rating options are visually represented.

Closes [#5503]

## Solution

Added aria labels to describe the rating options
Remove aria-required and aria-invalid labels by setting them as false (similar to our approach for radio buttons)
Updated Rating field container and Rating group to adopt aria-required and aria-invalid labels

**Breaking Changes** 

- [x] No - this PR is backwards compatible  

## Before & After Screenshots

**BEFORE**:

Recording 2023-02-14 at 15 53 57

**AFTER**:

Recording 2023-02-14 at 15 57 52

## Tests

On Mac, ensure voiceover is turned on:
- [ ] Go to a form with ratings set as required. Go through the ratings field and ensure that the required label is in the rating group (not each option).
- [ ] Try and submit form without indicating a rating (submission will fail). Voiceover will redirect to top of form. Go to ratings field and make sure 'invalid' label is together with the required label in the rating group (not each option). Select an option, submit the form.
- [ ] Go to a form with ratings, but not set as required. Go through the ratings field. Ensure that no required label is tagged on to the rating field (group or individual options). Submit the form.

On iOS, ensure voiceover is turned on:
- [ ] Go to a form with ratings set as required. Go through the ratings field and ensure that the required label is in the rating group. Ensure that each individual option do not read 'required' and do not read 'unticked' when it is selected.

### CODE REVIEW

File: frontend/src/components/Field/Rating/RatingOption.tsx [hunk 1]
```diff
@@ -202,6 +205,7 @@ export const RatingOption = forwardRef<RatingOptionProps, 'input'>(
         <input
           type="radio"
           aria-checked={selectedValue === value}
+          aria-label={`${value} ${variant}${value === 1 ? '' : 's'}`}
```
Comment (timotheeg) [inline frontend/src/components/Field/Rating/RatingOption.tsx]: /nitNothingToDo: Just a note that when (IF!) we ever introduce language localisation, pluralisation should not be done by concatenation.

**Review by timotheeg — APPROVED** [review]
LGTM

File: frontend/src/components/Field/Rating/RatingOption.tsx (hunk 1 above)
Comment (justynoh) [reply frontend/src/components/Field/Rating/RatingOption.tsx]: ndb but i wonder if we can use simplur for this? 
```javascript
aria-label={simplur`${value} ${variant}${[value]}[|s]`}

Comment (timotheeg) [reply frontend/src/components/Field/Rating/RatingOption.tsx]: ndb or nbd? 😜🤔
